# arduino + 25ga370电机参数配置(12v 空转620rpm/分钟)

port: /dev/ttyACM0
baud: 57600
timeout: 0.1

rate: 50
sensorstate_rate: 10

use_base_controller: True #启用基座控制器
base_controller_rate: 10

# For a robot that uses base_footprint, change base_frame to base_footprint
base_frame: base_footprint #base_frame 设置

# === 传动系统参数 Robot drivetrain parameters
wheel_diameter: 0.146    # 轮胎直径
wheel_track: 0.2969        # 两个轮胎间距
encoder_resolution: 8384 # 编码器精度(一圈的脉冲数 * 倍频 * 减速比)
#gear_reduction: 1.0      # 减速比
#motors_reversed: True    # 转向取反

# === PID parameters PID参数，控制轮速，修改到车子能够根据命令走直线且速度稳定
Kp: 10
Kd: 12
Ki: 0
Ko: 50
accel_limit: 1.0

# === Sensor definitions.  Examples only - edit for your robot.
#     Sensor type can be one of the follow (case sensitive!):
#	  * Ping
#	  * GP2D12
#	  * Analog
#	  * Digital
#	  * PololuMotorCurrent
#	  * PhidgetsVoltage
#	  * PhidgetsCurrent (20 Amp, DC)



sensors: {
  #motor_current_left:   {pin: 0, type: PololuMotorCurrent, rate: 5},
  #motor_current_right:  {pin: 1, type: PololuMotorCurrent, rate: 5},
  #ir_front_center:      {pin: 2, type: GP2D12, rate: 10},
  #sonar_front_center:   {pin: 5, type: Ping, rate: 10},
  arduino_led:          {pin: 13, type: Digital, rate: 5, direction: output}
}
